stages:
- build

firebase:
  stage: build
  only:
    - develop
  tags:
    - mac
  script:
    - git remote set-url --push origin git@gitlab.com:madbrains/lanta/smart-yard-ios.git
    - git remote get-url --push origin
    - bundle install
    - bundle exec fastlane firebase_release
  environment:
    name: ci

manual_firebase:
  stage: build
  when: manual
  tags:
    - mac
  script:
    - git remote set-url --push origin git@gitlab.com:madbrains/lanta/smart-yard-ios.git
    - git remote get-url --push origin
    - bundle install
    - bundle exec fastlane firebase_release
  environment:
    name: ci

tf:
  stage: build
  only:
    - master
  tags:
    - mac
  script:
    - git remote set-url --push origin git@gitlab.com:madbrains/lanta/smart-yard-ios.git
    - git remote get-url --push origin
    - bundle install
    - bundle exec fastlane tf_release
  environment:
    name: ci

manual_tf:
  stage: build
  when: manual
  tags:
    - mac
  script:
    - git remote set-url --push origin git@gitlab.com:madbrains/lanta/smart-yard-ios.git
    - git remote get-url --push origin
    - bundle install
    - bundle exec fastlane tf_release
  environment:
    name: ci
